services:
  db:
    image: postgres:15
    container_name: bolsa_talentos_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: bolsa_talentos
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/app/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql

  backend:
    build: ./backend
    container_name: bolsa_talentos_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres1234
      DB_NAME: bolsa_talentos
      DB_PORT: 5432
    depends_on:
      - db


      
  frontend:
    build: ./frontend
    container_name: bolsa_talentos_frontend
    ports:
      - "5173:5173"
  
    depends_on:
      - backend

volumes:
  db_data: