version: "3.9"

services:

  db:
    image: postgres:15
    container_name: jobs_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: bolsa_talentos
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/baseDatos/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: jobs_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  prolog:
    build: ./backend/prolog
    container_name: jobs_prolog
    stdin_open: true
    tty: true
    volumes:
      - ./backend/prolog:/app

  backend:
    build: ./backend
    container_name: jobs_backend
    restart: always
    depends_on:
      - db
      - prolog
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres1234
      DB_NAME: bolsa_talentos
      DB_PORT: 5435
    volumes:
      - ./backend:/app

  front:
    build: ./frontend
    container_name: jobs_front
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

volumes:
  db_data:
