version: "3.9"

services:
  db:
    image: postgres:15
    container_name: bolsa_talentos_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: bolsa_talentos
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/app/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    networks:
      - bolsa_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bolsa_talentos || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: bolsa_talentos_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bolsatalentos.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bolsa_net

  prolog-engine:
    build: ./backend/app/prolog
    container_name: bolsa_talentos_prolog
    ports:
      - "4000:4000"
    volumes:
      - ./backend/app/prolog/data:/app/data   # ← VOLUMEN LOCAL COMPARTIDO
    networks:
      - bolsa_net
    restart: unless-stopped
    # Agregar dependencia y healthcheck
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: bolsa_talentos_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres1234
      DB_NAME: bolsa_talentos
      DB_PORT: 5432
      DATABASE_URL: postgresql://postgres:postgres1234@db:5432/bolsa_talentos
      PROLOG_URL: http://prolog-engine:4000
      BACKEND_URL: http://backend:3000
    volumes:
      - ./backend/app/prolog/data:/app/prolog_data   # ← MISMA CARPETA LOCAL
    networks:
      - bolsa_net
    depends_on:
      db:
        condition: service_healthy
      prolog-engine:
        condition: service_started

  frontend:
    build: ./frontend
    container_name: bolsa_talentos_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - bolsa_net
    depends_on:
      - backend

volumes:
  db_data:

networks:
  bolsa_net:
    driver: bridge